### ISSUE TITLE
SelectFeatureExample stopped working with v4.8.0-alpha.1

### ISSUE THREAD

**Issue by fabian-guerra** [mapbox/ios-sdk-examples#263] opened 2019-01-10 17:40 UTC
The example `SelectFeatureExample` on both objc and swift with the SDK version `4.8.0-alpha.1` stopped working.

**Comment by captainbarbosa** [comment] 2019-01-25 15:09
I can't reproduce this issue on my iPhone X on iOS v12.1.2 🤔

**Comment by friedbunny** [comment] 2019-01-25 22:37
Perhaps https://github.com/mapbox/ios-sdk-examples/pull/269.

**Comment by friedbunny** [comment] 2019-01-25 22:38
Err, no — `SelectFeatureExample` _is a different example_ than `FeatureSelectionExample`... 🤨

... perhaps it’s time to rationalize these names.

**Comment by fabian-guerra** [comment] 2019-01-25 23:09
I was referring to "Select a park feature" (`SelectFeatureExample_Swift`/`SelectFeatureExample.m`, I checked today with `java-beta.1` and I can still reproduce the issue. Perhaps is something similar to #269

**Comment by jmkiley** [comment] 2019-01-26 00:13
It doesn't look like the `SelectFeatureExample` is pinned to a Mapbox Streets style version, so it may be broken for Mapbox Streets v11. Setting the style URL for the Objective-C example to `[MGLStyle streetsStyleURLWithVersion:10];` seems to fix it for me.

**Comment by jmkiley** [comment] 2019-02-04 21:21
Addressed in #270

**Closed by jmkiley** 2019-02-04 21:22 UTC
Labels: bug
