### ISSUE TITLE
Create offline example using a multipolygonal offline region

### ISSUE THREAD

**Issue by julianrex** [mapbox/ios-sdk-examples#280] opened 2019-03-15 19:36 UTC
@1ec5 Hi, I'm having performance issues downloading too many offline regions, could you please share some example of the multipolygon approach?

_Originally posted by @pedrocruzlopez in https://github.com/mapbox/mapbox-gl-native/issues/6651#issuecomment-473373677_

**Comment by captainbarbosa** [comment] 2019-03-25 21:52
Is this the same as https://github.com/mapbox/ios-sdk-examples/issues/280?

**Comment by captainbarbosa** [comment] 2019-03-26 15:12
Duplicate of https://github.com/mapbox/ios-sdk-examples/issues/206?

**Closed by captainbarbosa** 2019-03-26 15:12 UTC
